ProjetoReformulado/ProjetoReformulado/Models/ItemModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace ProjetoReformulado.Models
{
    public class ItemModel
    {
        public int Id { get; set; }
        [MaxLength(100, ErrorMessage = "O nome do item não pode conter mais de 100 caracteres")]
        [DisplayName("Nome do Item")]
        [Required(ErrorMessage = "Informe um nome")]
        [RegularExpression(@"^[aA-zZ]+((\s[aA-zZ]+)+)?$", ErrorMessage = "O nome do item não pode conter números")]
        public string Nome { get; set; }
    }
}

ProjetoReformulado/ProjetoReformulado/Controllers/ItemController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProjetoReformulado.Controllers
{
    public class ItemController : Controller
    {
        Business.ItemBusiness business = new Business.ItemBusiness();
        string resultado = "OK";
        List<string> mensagem = new List<string>();

        // Carrega a exibição inicial
        public ActionResult Início()
        {
            if (!ModelState.IsValid)
            {
                resultado = "AVISO";
                mensagem = ModelState.Values.SelectMany(x => x.Errors).Select(x => x.ErrorMessage).ToList();
            }
            else
            {
                try
                {
                    List<Models.ItemModel> lista = business._ListarTodos();
                    return View(lista);
                }
                catch (Exception)
                {
                    resultado = "Não foi possível iniciar o programa";
                }
            }

            return Json(new { Resultado = resultado, Mensagem = mensagem });
        }

        // Carrega a exibição de inserir um item
        public ActionResult InserirItem()
        {
            if (!ModelState.IsValid)
            {
                resultado = "AVISO";
                mensagem = ModelState.Values.SelectMany(x => x.Errors).Select(x => x.ErrorMessage).ToList();
            }
            else
            {
                try
                {
                    return View();
                }
                catch (Exception)
                {

                    resultado = "Não foi possível acessar essa tela";
                }
            }

            return Json(new { Resultado = resultado, Mensagem = mensagem });
        }

        // Executa a ação de inserir quando o botão é clicado
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult InserirItem(Models.ItemModel item)
        {
            // ModelState.AddModelError("", "Item inválido.");
              if (!ModelState.IsValid)
              {
                resultado = "AVISO";
                mensagem = ModelState.Values.SelectMany(x => x.Errors).Select(x => x.ErrorMessage).ToList();
              }
              else
              {
                try
                {
                    business.InserirItem(item);
                    return RedirectToAction("Início");

                }
                catch (Exception)
                {
                    resultado = "Não foi possível inserir esse item";
                    
                }
              }
            return View();
            //return Json(new { Resultado = resultado, Mensagem = mensagem });                 
        }

        // Carrega a exibição dos itens 
        public ActionResult _ListarTodos()
        {
            if (!ModelState.IsValid)
            {
                resultado = "AVISO";
                mensagem = ModelState.Values.SelectMany(x => x.Errors).Select(x => x.ErrorMessage).ToList();
            }
            else
            {
                try
                {
                    List<Models.ItemModel> lista = business._ListarTodos();
                    return View(lista);
                }
                catch (Exception)
                {
                    resultado = "Não foi possível listar os itens";
                }
            }

            return Json(new { Resultado = resultado, Mensagem = mensagem });
        }

        // Carrega a exibição de alterar um item
        public ActionResult AlterarItem(int id)
        {
            if (!ModelState.IsValid)
            {
                resultado = "AVISO";
                mensagem = ModelState.Values.SelectMany(x => x.Errors).Select(x => x.ErrorMessage).ToList();
            }
            else
            {
                try
                {
                    Models.ItemModel model = business.FiltrarPorId(id);
                    return View(model);
                }
                catch (Exception)
                {
                    resultado = "Não foi possível acessar essa opção";
                }
            }

            return Json(new { Resultado = resultado, Mensagem = mensagem });
        }

        // Executa a ação de alterar quando o botão é clicado
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AlterarItem(Models.ItemModel item)
        {
            if (!ModelState.IsValid)
            {
                resultado = "AVISO";
                mensagem = ModelState.Values.SelectMany(x => x.Errors).Select(x => x.ErrorMessage).ToList();
            }
            else
            {
                try
                {
                    business.AlterarItem(item);
                    return RedirectToAction("Início");
                }
                catch (Exception)
                {
                    resultado = "Não foi possível inserir esse item";
                }
            }

            return Json(new { Resultado = resultado, Mensagem = mensagem });
        }

        // Carrega a exibição de remover um item
        public ActionResult RemoverItem(int id)
        {
            if (!ModelState.IsValid)
            {
                resultado = "AVISO";
                mensagem = ModelState.Values.SelectMany(x => x.Errors).Select(x => x.ErrorMessage).ToList();
            }
            else
            {
                try
                {
                    Models.ItemModel model = business.FiltrarPorId(id);
                    return View(model);
                }
                catch (Exception)
                {
                    resultado = "Não foi possível acessar essa opção";
                }
            }

            return Json(new { Resultado = resultado, Mensagem = mensagem });
        }

        // Executa a ação de remover quando o botão é clicado
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult RemoverItem(int id, Models.ItemModel item)
        {         
           try
           {
               business.RemoverItem(id);
               return RedirectToAction("Início");
           }
           catch (Exception)
           {
              resultado = "Não foi possível remover esse item";
              return Json(new { Resultado = resultado, Mensagem = mensagem });
           }
        }        
    }
}

ProjetoReformulado/ProjetoReformulado/Views/Item/AlterarItem.cshtml
@model ProjetoReformulado.Models.ItemModel

@{
    ViewBag.Title = "AlterarItem";
}

<h2>Alterar um Item</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Alterar" class="btn btn btn-success" />
            </div>
        </div>
    </div>
}

<br />

<div>
    @Html.ActionLink("Voltar", "Início")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ProjetoReformulado/ProjetoReformulado/Views/Item/InserirItem.cshtml
@model ProjetoReformulado.Models.ItemModel

@{
    ViewBag.Title = "InserirItem";
}

<h2>Novo item</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Cadastrar" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Voltar", "Início")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ProjetoReformulado/ProjetoReformulado/Views/Item/Início.cshtml
@{
    ViewBag.Title = "Início";
}
<center>
    <h2 class="Início">
        <span id="lista">TO DO LIST</span>
    </h2>
</center>

<br />

<br />

<div id="AdicionarItem">
    @Html.ActionLink("Novo Item", "InserirItem", "Item")
</div>

<br />

<br />

<center>
        <h3>
            <span id="Itens">Lista de Itens</span>
        </h3>
</center>

<br />

<p>
    @Html.Partial("_ListarTodos")
</p>

ProjetoReformulado/ProjetoReformulado/Views/Item/RemoverItem.cshtml
@model ProjetoReformulado.Models.ItemModel

@{
    ViewBag.Title = "RemoverItem";
}

<h2>Remover um Item</h2>

<br />

<h3>Tem certeza que deseja remover esse item?</h3>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nome)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Remover" class="btn btn btn-success" />
        </div>
    }
</div>

<br />

<div>
    @Html.ActionLink("Voltar", "Início")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ProjetoReformulado/ProjetoReformulado/Views/Item/_ListarTodos.cshtml
@model IEnumerable<ProjetoReformulado.Models.ItemModel>

<table class="table table-bordered table-striped table-hover">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nome)
            </th>
            <th id="ações"> Ações</th>
        </tr>
    </thead>
    <tbody>
    @{
        if (Model != null)
        {
          foreach (var item in Model)
          {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Nome)
                </td>
                <td id="opções">
                    @Html.ActionLink("Editar", "AlterarItem", new { id = item.Id }, new { @class = "btn btn-warning" })
                    @Html.ActionLink("Remover", "RemoverItem", new { id = item.Id }, new { @class = "btn btn-danger" })
                </td>
            </tr>
          }
        }
    }
    </tbody>
</table>

ProjetoReformulado/ProjetoReformulado/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - To Do List</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - To do List</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    @Scripts.Render("~/bundles/jquery")
</body>
</html>